### ISSUE TITLE
Pose messages

### ISSUE THREAD

**Issue by marija-p** [ethz-asl/geodetic_utils#15]
gps_to_pose_conversion node publishes GPS pose messages with orientation which are not being used in our programs. Should we modify this to publish position only? @enricgalceran

**Comment by marija-p** [comment]
@enricgalceran  Just saw that this is still an outstanding issue. Would the right way of handling it be to create a parameter signifying to publish pose or not, as we did for gps_spoofer.py?

**Comment by enricgalceran** [comment]
Yes, you can do the same thing here.

**Comment by marija-p** [comment]
Issue resolved in PR  GPS publish_pose param #23 .
