### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by pallyra1** [ethz-asl/geodetic_utils#33]
With the current CMakeLists.txt, upon using the command **catkin_make**, I am getting **CMake error**.
I am new to ROS.
I am unable to use this package.
I want to convert lat&lon to ECEF to ned coordinates.
Please help.

**Comment by ZacharyTaylor** [comment]
Try using "catkin build" instead. All of our tools were designed to be compiled using "catkin build" and most will not work with catkin_make

**Comment by pallyra1** [comment]
Upon building, I am getting this..

CMake Error at geodetic_utils/CMakeLists.txt:7 (find_package):
  By not providing "Findcatkin_simple.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "catkin_simple", but CMake did not find one.

  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/pallav/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pallav/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:906: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

**Comment by ZacharyTaylor** [comment]
This package has two dependecies: Eigen and catkin_simple
You can find catkin_simple here https://github.com/catkin/catkin_simple

**Comment by pallyra1** [comment]
It worked.
Thank you so much.
